[tools]
"aqua:mfontanini/presenterm" = "latest"
"pipx:weasyprint" = "latest"

[tasks.presentation]
description = "Present the slides"
run = "presenterm slides.md"

[tasks.pdf]
description = "Export presentation PDF"
run = "presenterm --export-pdf slides.md"

[tasks.demo]
description = "Create recordings with vhs"
run = """
#!/usr/bin/env bash

if ! docker info > /dev/null 2>&1; then
  echo "This script uses docker, and it isn't running - please start docker and try again!"
  exit 1
fi

vhs() {
    docker run --rm -v $(pwd)/tapes/:/data -w /data ghcr.io/charmbracelet/vhs "$@"
}

# Create VHS recordings of all tape files in the directory
for i in $(ls -1 tapes/*.tape); do
    vhs $(basename $i .tape).tape
done
"""
